version: "3.8"
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=gnobs7cbfedmtb5lm424
      - POSTGRES_PASSWORD=pscale_pw_uIxkLKZT4Lh8jpaxXKW21Ww0cnFwGeXl6CwSr7xO2jk
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
